language: php

php:
  - 5.6
  - 7.0
  - 7.1
    env: ANALYSIS='true'

install:
  - composer update

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - if [[ "$ANALYSIS" == 'true' ]]; travis_retry php vendor/bin/coveralls -v ; fi
