sudo: false

language: php

dist: trusty

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: ANALYSIS='true'

before_script:
  - mkdir -p build/logs
  - composer update

script:
  - if [[ "$ANALYSIS" != 'true' ]]; then vendor/bin/phpunit ; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover /home/travis/build/mathmarques/teste-software/clover.xml ; fi

after_script:
  - if [[ "$ANALYSIS" == 'true' ]]; then php vendor/bin/coveralls --coverage_clover=/home/travis/build/mathmarques/teste-software/clover.xml -v -r=/home/travis/build/mathmarques/teste-software; fi
